### ISSUE TITLE
Drive motor enable pin from digital output 

### ISSUE THREAD

**Issue by jspall0327** [RoboJackets/software-training-hardware#9]

**Comment by barulicm** [comment]
If the current problem is uncontrollable / random uController outputs while it loads the firmware, would this actually fix it?

**Comment by jspall0327** [comment]
It might. Not really sure. But we should probably stop motors on disconnect and stuff anyway.

**Comment by JasonGibson274** [comment]
We already stop motors on disconnect from the firmware. We might want to check if there is an open pin that does not randomly do this first. If all pins behave the same then there might be nothing we can do.
